coderedcorp/coderedcms

coderedcms/models/snippet_models.py
coderedcms/wagtail_hooks.py

Fixes #16 
Also removes a duplicate definition for `ContentWall`.  Not sure how the model definition was duplicated, probably some merge error.

16 fix document viewing

---

coderedcms/templates/coderedcms/blocks/pagelist_block.html

Found this typo while using **Latest Pages** from Content `StreamField`

Edited typo for pagelist_block.html

---

coderedcms/models/page_models.py

Not exactly a bug, but discovered this while debugging a client site. Updated the edit handler definitions to follow the examples in the wagtail docs.

Standardize edit handler definitions

---

README.md
coderedcms/bin/coderedcms.py
coderedcms/project_template/.gitattributes
coderedcms/project_template/.gitignore
coderedcms/project_template/Dockerfile
coderedcms/project_template/README.md
coderedcms/project_template/project_name/settings/base.py
coderedcms/project_template/project_name/settings/dev.py
coderedcms/project_template/project_name/settings/prod.py
coderedcms/project_template/project_name/urls.py
coderedcms/project_template/website/migrations/0002_initial_data.py
docs/_static/docs.css
docs/getting_started/install.rst

The goal of this is to get the boilerplate project more functional out of the box.
* Added boilerplate README, .gitattributes and .gitignore
* Refactored coderedcms command to add `--sitename` and `--domain` options to pre-populate a human readable name and domain name in the settings, README, and initial migration that creates the Site and Home Page. With this new command we can build an entire context for the project_template, the sky is the limit.
These changes should save us time and reduce one additional step of human error having to change settings per project, and should also be more friendly to beginners who are getting started. This also fixes a bug in the default prod.py settings (that's how it all started, then I went down the rabbit hole!)
Just experimenting here, I think it …

Enhancing project template

---

coderedcms/static/css/codered-admin.css
coderedcms/static/css/codered-editor.css

Should fix issues highlighted in #61 
Wagtail 2.4 started using a `.label-above` class, which this is tuned for, which greatly fixes the layout of the image editing page without us having to sacrifice streamfield label styles. These changes are compatible with both wagtail 2.3 and 2.4, but will provide more benefit to 2.4.
The main things that cause so much custom css at this point are:
1. using flexbox on labels/inputs so they render side-by-side nicely. Without this our deeply nested streamfields become ridiculously long and difficult to edit.
2. Making input boxes less padded and higher contrast. Once again, thick chunky inputs with an ultra-light font and super-light colors take up too much space and are difficult to read once they are nested in the streamfield.
3. Support the ability …

Removing some custom admin css to be more compatible with wagtail

---

coderedcms/templates/coderedcms/pages/form_page.html

Form page currently over-writes title and other content blocks form `web_page.html` template. One side effect is the title and cover image do not show. After this fix the form will properly get appended to the content body.

Better inheritance on form page template

---

coderedcms/models/page_models.py
setup.py

Fixes #97 . Updating to wagtail-cache 0.4 to fix caching issues.
Never cache form pages due to various complexities (CSRF token, potential view restrictions, changing template/content based on form validation or thank you page, etc).
Also added missing `wheel` package from dev extras.

Fix cache issues

---

coderedcms/models/page_models.py
coderedcms/static/js/codered-maps.js
coderedcms/templates/coderedcms/pages/location_index_page.html

Adding block to easier add more robust HTML when no results are found on location_index_page.html.
Consequently, this ended up exposing a bug in the modified `get_index_children()` behavior. It was not using the specified querymodel and was falling back to `get_children()` since the new default ordering is blank. Bug is fixed, and I believe it improves the behavior.
Side note: js file has been linted so the diff looks crazy... relevant change is in the `updateList()` function. Everything else is unchanged except for formatting.

Enhance store finder no results

---

coderedcms/views.py

Ordering is done on queryset before doing the search. The search backend is still free to reorder the results, however I don't believe the database search backend does any ordering.
When searching on a specific model, do not order, the assumption is the models' Meta ordering will be used.

Order default search model (CoderedPage) by last published date new->old

---

coderedcms/templates/coderedcms/pages/form_page_landing.html

Moved from block `content` to `content_body` to better match normal form page. Fixed misspelling and also removed unused template tags

Form landing content

---

coderedcms/models/page_models.py
coderedcms/project_template/project_name/settings/base.py
coderedcms/urls.py
setup.py

This upgrade fixes issue #118 and enhances caching by updating to wagtailcache 0.5 and using the new middleware by default.
Advantages:
* We can now remove duplicated wagtail URLs from urls.py
* New middleware caches 301/302 redirects and 404 pages.
* New middleware properly caches CSRF tokens so form pages should not need any additional logic.

Updating to wagtailcache 0.5

---

coderedcms/templates/coderedcms/includes/struct_data_event.json

Noticed that there was a minor syntax error causing google structured data failure.

Fixing json syntax error on event markup

---

coderedcms/templates/coderedcms/blocks/base_link_block.html
coderedcms/templates/coderedcms/snippets/navbar.html
coderedcms/templatetags/coderedcms_tags.py

Adds an `active` CSS class to page links in the navbar when on that same page.
Also fixed bug where non-pages would not render in the top level navbar (due to `{% if item.value.page.live %}` check)

Highlight active navbar links

---

.coveragerc
.travis.yml
setup.py

```codecov``` is installed by travis because it's never used outside the CI environment.

Add basic codecov files

---

coderedcms/project_template/project_name/settings/base.py
coderedcms/templates/coderedcms/pages/base.html
coderedcms/tests/settings.py
docs/getting_started/customize_develop.rst

in settings.py
-changed i18n to True so that international users can access admin in preferred language
in base.py
-changed LANGUAGE_CODE to LANGUAGES list with tuples of possible project languages (leaving 'en' as default)
- to change the default page language, remove the 'en' tuple and add in your preferred language
in base.html
-used i18n to get_current_language from user's browser, and if it is one of the languages in LANGUAGES in base.py, the browser will use that language in the html tags
-if user's current language is not available to that project, the language set in base.py will stay set in the html tags
[django translation doc](https://docs.djangoproject.com/en/2.2/topics/i18n/translation/)

adding language to html tag and i18n

---

coderedcms/templates/coderedcms/pages/article_page.html
coderedcms/templates/coderedcms/pages/base.html
coderedcms/templatetags/coderedcms_tags.py

- added meta tags to base to comply with twitter requirements and called up new template tag, twitter_card_image
- twitter_card_image first tries to use cover image in twitter card, if not uses website logo
- per request, cleaned up the Open Graph image meta tag logic to check for OG image, then cover photo, then logo in the same way as the twitter_card_image.
- article page runs also runs twitter_card_image and adjusts the twitter card to use summary_large_image

twitter card adjusted to render images

---

coderedcms/templates/coderedcms/blocks/base_link_block.html
coderedcms/templates/coderedcms/blocks/button_block.html
coderedcms/templates/coderedcms/blocks/column_block.html
coderedcms/templates/coderedcms/blocks/document_link_block.html
coderedcms/templates/coderedcms/blocks/download_block.html
coderedcms/templates/coderedcms/blocks/external_link_block.html
coderedcms/templates/coderedcms/blocks/google_map.html
coderedcms/templates/coderedcms/blocks/h1_block.html
coderedcms/templates/coderedcms/blocks/h2_block.html
coderedcms/templates/coderedcms/blocks/h3_block.html
coderedcms/templates/coderedcms/blocks/hero_block.html
coderedcms/templates/coderedcms/blocks/page_link_block.html
coderedcms/templates/coderedcms/includes/codered_banner.html
coderedcms/templates/coderedcms/includes/stream_forms/render_field.html
coderedcms/templates/coderedcms/pages/base.amp.html
coderedcms/templates/coderedcms/pages/base.html
coderedcms/templates/coderedcms/snippets/footer.html
coderedcms/templates/coderedcms/snippets/navbar.html
coderedcms/templatetags/coderedcms_tags.py

Should mostly fix issue #209
* Removing newlines in template tags when rendering them inside html attributes;
* convert tabs to spaces in html files;
* cleanup whitespace in html where appropriate

Cleanup whitespace in HTML templates

---

coderedcms/models/page_models.py
docs/how_to/index.rst
docs/how_to/translation.rst
docs/index.rst

I haven't included the `coderedcms/project_template/basic/website/models.py` in the PR, but have a look at its content, specifically at the panel overriding required to actually show the "body" `content_panel`. I added it for each relevant back office page model's creation / edit view.
Please note that users wanting to install `wagtail-modeltranslation` with CoderedCMS wouldn't find instructions anywhere about the code below.
How would you like to proceed about this? 
```
"""
Createable pages used in CodeRed CMS.
"""
from modelcluster.fields import ParentalKey
from coderedcms.forms import CoderedFormField
from coderedcms.models import (
CoderedArticlePage,
CoderedArticleIndexPage,
CoderedEmail,
CoderedFormPage,
CoderedWebPage
)
class ArticlePage(CoderedArticlePage):
"""
Article, suitable …
```

Compatibility with wagtail_modeltranslation

---

coderedcms/templates/coderedcms/blocks/pagepreview_form.html

Found one bug while testing, the page preview block is missing the honeypot when showing a form preview.

Adding honeypot to page preview block (form)

---

coderedcms/templatetags/coderedcms_tags.py

Prepends the root URL to the URLs generated for OG images, unless `MEDIA_URL` already looks like a valid (base) URL. Typically `MEDIA_URL` is just `/media/` in the default Django ( and CodeRedCMS ) projects. But for cases where users have specified a `MEDIA_URL` that contains e.g. `https://s3.amazonaws.com/my-bucket-here/`, we don't need to prepend the root URL.

Fixes #240 absolute URLs of OG images.

---

azure-pipelines.yml
ci/compare-artifacts.ps1
ci/compare-codecov.ps1
docs/contributing/index.rst

[Found an API](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/Code%20Coverage/Get%20Build%20Code%20Coverage?view=azure-devops-rest-5.1) that somehow magically pulls the code coverage. Seems to work better than trying to download the artifact from the master branch. This should work better on external pull requests (See https://github.com/MicrosoftDocs/vsts-docs/issues/5588). Plus we have the advantage of being able to run it locally now to compare code coverage before committing.
Updated contributor guide.

Fix pipeline code coverage comparison

---

coderedcms/templates/coderedcms/blocks/embed_video_block.html
coderedcms/templates/coderedcms/blocks/rich_text_block.html
coderedcms/templates/coderedcms/pages/article_page.amp.html
coderedcms/templatetags/coderedcms_tags.py
coderedcms/tests/test_utils.py
coderedcms/utils.py
docs/releases/v0.17.0.rst

Fixes issue #254 
Additional unit tests also now test the AMP conversion function.
Added documentation to 0.17 release notes.
Original work took place in #255  - splitting relevant parts out into separate PRs/commits.

Improve AMP rendering of richtext, embed blocks

---

coderedcms/static/coderedcms/css/codered-admin.css
coderedcms/static/coderedcms/css/codered-editor.css

Previously we had the labels and fields aligned horizontally (side-by-side), to make the page editor more compact for long pages.
With the new streamfield design, this change will stack nested streamfields to avoid wasting the large amount of dead space under the streamfield's label. Also enhanced the hover shadow effect to create more visual contrast with deeply nested streamfields.
See issue #280 
Fixes #280

Stack nested streamfields under label

---

coderedcms/templates/coderedcms/blocks/card_block.html
coderedcms/templates/coderedcms/blocks/card_blurb.html
coderedcms/templates/coderedcms/blocks/card_foot.html
coderedcms/templates/coderedcms/blocks/card_head.html
coderedcms/templates/coderedcms/blocks/card_head_foot.html
coderedcms/templates/coderedcms/blocks/card_img.html
coderedcms/templates/coderedcms/blocks/google_map.html
coderedcms/templates/coderedcms/blocks/h1_block.html
coderedcms/templates/coderedcms/blocks/h2_block.html
coderedcms/templates/coderedcms/blocks/h3_block.html
coderedcms/templates/coderedcms/blocks/hero_block.html
coderedcms/templates/coderedcms/blocks/image_block.html
coderedcms/templates/coderedcms/blocks/image_gallery_block.html
coderedcms/templates/coderedcms/blocks/pagepreview_card.html
coderedcms/templates/coderedcms/blocks/table_block.html

Corrects attributes set for custom CSS classes or custom IDs.
As promised per https://github.com/coderedcorp/coderedcms/issues/275 , unifies the custom CSS and ID attributes. Pulls from `self.settings` consistently, and also uses `custom_id` rather than `custom_css_id`.

Corrects attributes set for custom CSS classes or custom IDs.

---

coderedcms/templates/coderedcms/blocks/card_block.html
coderedcms/templates/coderedcms/blocks/card_blurb.html
coderedcms/templates/coderedcms/blocks/card_foot.html
coderedcms/templates/coderedcms/blocks/card_head.html
coderedcms/templates/coderedcms/blocks/card_head_foot.html
coderedcms/templates/coderedcms/blocks/card_img.html
coderedcms/templates/coderedcms/blocks/google_map.html
coderedcms/templates/coderedcms/blocks/h1_block.html
coderedcms/templates/coderedcms/blocks/h2_block.html
coderedcms/templates/coderedcms/blocks/h3_block.html
coderedcms/templates/coderedcms/blocks/hero_block.html
coderedcms/templates/coderedcms/blocks/image_block.html
coderedcms/templates/coderedcms/blocks/image_gallery_block.html
coderedcms/templates/coderedcms/blocks/pagepreview_card.html
coderedcms/templates/coderedcms/blocks/table_block.html

1. It is `custom_id` instead of `custom_css_id` in some of the block templates file.
2. we should fetch `custom_id` and `custom_css_class` attributes from the settings.

Fix block custom attr typo

---

coderedcms/templates/coderedcms/blocks/reusable_content_block.html

My commit yesterday, #de36594 - a partial fix to #275, fixed the custom CSS and ID, but introduced a bug where the snippet name was rendered, not the content.  
This fixes that.
My apologies.
Create and include an HTML reusable content, setting a CSS, an ID, and a piece of content. Ensure that all three attributes are rendered to HTML.

render html snippet contents rather than the snippet name.

---

MANIFEST.in
azure-pipelines.yml
coderedcms/models/page_models.py
coderedcms/project_template/basic/project_name/settings/base.py
coderedcms/project_template/sass/project_name/settings/base.py
coderedcms/static/coderedcms/css/codered-admin.css
coderedcms/templates/coderedcms/pages/base.html
coderedcms/templates/coderedcms/snippets/navbar.html
coderedcms/templates/wagtailadmin/base.html
coderedcms/templates/wagtailadmin/shared/menu_settings_menu_item.html
coderedcms/templatetags/coderedcms_tags.py
coderedcms/views.py
docs/contributing/index.rst
docs/releases/v0.19.0.rst
requirements-ci.txt
requirements-dev.txt
setup.py

* Upgrade to Wagtail 2.9
* Remove deprecated use of `SiteMiddleware` and `request.site`.
* Pin/update/remove dependencies as needed.
* Move extras out of setup.py and into requirement files. This was not an appropriate use of the extras.
Fixes #330 and #324

Upgrade to Wagtail 2.9

---

coderedcms/templates/coderedcms/blocks/google_map.html
docs/releases/v0.19.0.rst

Fixes #220 
Tested manually and confirmed issue is fixed. This would be a great test for adding block unit tests.

Fix google map CSS class and API key in HTML templates

---

coderedcms/models/page_models.py

Explain what you changed, and how or why it works the way it does.
submitting a form as anonymous user doesn't work. (error 500)
The problem is that the anonymous user doesn't have a session  yet

Fix submit form with file uploads for anonymous users

---

coderedcms/tests/test_urls.py
coderedcms/views.py

Fixes #387 
1) Updated the exception in search to be contentype.doesnotexist so that if someone adds search parameters into the search URL, it returns a 200 page with "no results found" instead of Internal Service Error
2) Added the test for it in the test_search function in test_urls.py
n/a
Test added to the def test_search function to test for "/search/?s=keyword&t=t"
Also tested this manually and it works. The search box was fine. It was a bug when people typed in search parameters in the URL for search.

Fix search 500 error with invalid query

---

coderedcms/static/coderedcms/css/codered-admin.css
coderedcms/templates/wagtailadmin/shared/main_nav.html
docs/features/page_types/article_pages.rst

Foot menu items on branch wagtail-upgrade213 is not pinned to the bottom.
Wagtail 2.13 uses 'nav-footer' and 'nav-footer-menu' classes instead of the current 'footer' and 'footer-menu' class in coderedcms.

Fix foot menu position

---

docs/releases/v0.22.0.rst
setup.py

As far as I can tell, there are no major changes from 2.13 -> 2.14, so it is an easy upgrade. Fixes #428 .
Everything seems to visually work in the admin.
I did patch in #431 which I discovered while auditing 2.14 changes, so that has been merged into dev and backported to 0.21.1.

Upgrade to Wagtail 2.14

---

coderedcms/static/coderedcms/css/codered-admin.css
coderedcms/templates/wagtailadmin/base.html
docs/releases/v0.22.0.rst

The Navbar color scheme setting is used in the front-end (by bootstrap) to color the navbar which sits behind the logo. Generally speaking, if the logo is dark a light navbar is used, if the logo is light a dark navbar is used.
We also show the client's logo in the wagtail admin, as a friendly sight, and also to help differentiate multiple wagtail admins.
However, dark logos are usually unreadable or look terrible against the dark-gray wagtail admin. This change draws a light background behind the logo in the wagtail admin when the light navbar color scheme is selected.

Use navbar color scheme setting to draw background of logo

---

coderedcms/wagtail_hooks.py
docs/releases/v0.22.0.rst

Fixes #434 
Previously we were only clearing the cache when pages were created or edited.
Now we will clear the cache whenever pages are: published, unpublished, moved, deleted; or snippets are: created, edited, deleted.
This should help make the cache more invisible to editors who sometimes need to file support requests because changes are not immediately visible across the site.

Clear wagtailcache on page and snippet changes

---

coderedcms/static/coderedcms/js/codered-front.js
coderedcms/templates/coderedcms/pages/base.html
coderedcms/wagtail_hooks.py
docs/releases/v0.22.0.rst

This should have been done long ago, but it now adds a version identifier as a querystring on all css/js files which are part of the coderedcms package, to ensure that they are re-fetched by the browser after upgrading coderedcms on a client site. E.g.
```
/codered-front.js?v=0.22.0
```
Tested locally and confirmed presence of querystrings.

Cache-bust provided css/js files

---

coderedcms/models/page_models.py
docs/releases/index.rst
docs/releases/v0.22.2.rst

Due to a refactor in the form email sending functionality, an invalid content subtype was being set on the message for plaintext emails. Therefore form submission emails appeared to have no contents, and the contents were instead attached as a text file. This fix corrects the content subtype attribute.
This change also fixes a related but separate behavior to correctly display the field labels within the summary email message. Previously they were being humanized from the dict key (e.g. replace underscores with spaces). Now they are being pulled from the actual form labels.
Manually tested, using Outlook email client.

Fix form summary emails

---

coderedcms/static/coderedcms/css/codered-admin.css
docs/releases/v0.22.2.rst

In some situations, streamfields may appear center-aligned instead of left-aligned. This seems to have broken due to some kind of rendering change in recent versions of Wagtail.
Tested Wagtail admin manually on problematic sites in Firefox and Chrome.

Fix rendering of some streamfields

---

coderedcms/models/page_models.py
docs/releases/index.rst
docs/releases/v0.22.3.rst

Due to change in 0.22.2, forms which override `get_form_fields()` method and do NOT return fields as `AbstractFormField` class would cause breakage while sending the summary email. Now, the actual Django form object is used instead rather than the `get_form_fields()` method, which should make it more widely compatible with custom page types.

Fix email sending of form page models which provide custom get_form_fields() method

---

coderedcms/views.py
docs/releases/v0.22.3.rst

Prevent upward path traversals when serving protected media

---

docs/releases/v0.20.0.rst

Added upgrade consideration to coderedcms v. 0.20.0 release notes
documentation, please provide a description here instead. Upgrading from 0.19.0 to newer versions of CoderedCMS causes an issue with forms/form data because of the upgrade to Wagtail 2.11.

added upgrade consideration to coderedcms v. 0.20.0 release notes

---

coderedcms/models/page_models.py
coderedcms/models/snippet_models.py

Make orderables save correctly the order. Due to the overwritting of Meta class, orderables didn't have the needed ordering variable. Here is the description of the [Orderable bug](https://github.com/wagtail/wagtail/issues/1749) in Wagtail repo.
N/A
N/A

fix orderables, need to inherit Meta to work correctly

---

coderedcms/admin_urls.py
coderedcms/importexport.py
coderedcms/project_template/basic/project_name/urls.py
coderedcms/project_template/sass/project_name/urls.py
coderedcms/search_urls.py
coderedcms/urls.py
coderedcms/views.py
coderedcms/wagtail_flexible_forms/wagtail_hooks.py
setup.py

* Fix for Django 4.0
* Replace some unnecessary `re_path` with `path`

Django 4.0 compatible

---

coderedcms/wagtail_hooks.py

Remove `CoderedFormAdmin` and `CoderedSubmissionAdmin` from `wagtail_hooks.py`. These are not used internally and are not publicly documented.

Remove dead code from wagtail_hooks

---

coderedcms/models/page_models.py
coderedcms/templates/coderedcms/pages/search.html
coderedcms/templates/coderedcms/pages/search_result.html
coderedcms/templatetags/coderedcms_tags.py
coderedcms/views.py
docs/features/searching.rst

In Wagtail 2.16, they overhauled the search functionality to be able to properly search multiple different Page types. We had implemented this feature in a work around method locally in CRX, which is no longer necessary.
Fixes #82 
This change:
1. Removes the workaround to use Wagtail's search directly.
2. Maintains existing legacy behavior for page type filtering, but also allows filtering of non-CRX page types.
3. Deprecates several attributes from CRX Page models that are no longer necessary
Updated search documentation to be in line with new functionality/deprecation.
A unit test for the search endpoint already exists, this cod change was made in line with it.

Search all Wagtail Page models

---

coderedcms/tests/test_urls.py
coderedcms/urls.py
coderedcms/views.py

Fixes #503 
Bots end up blasting garbage into these ajax views, which causes unnecessary server errors and/or database queries.
* Add validation and error handling to POST and GET parameters in event ajax views.
* Add unit tests.

Event ajax views error handling

---

coderedcms/models/page_models.py
coderedcms/views.py

Fixes #467 
As it stands, Outlook for Mac has a higher standard of compliance to the iCalendar standard, which our EventOccurencePage exports to. This higher standard was causing imported event for our .ics files to fail on calendar sync, and be deleted from the calendar. 
To correct this three things have been changed:
1. Additional fields have been added to the calendar (prodid and version), which are required for compliance.
2. Additional fields have been added to the event (dtstamp and uid) which are required for compliance.
3. The datetimes presented for dt_start and dt_end have been converted to UTC. The existing timezoned datetimes were being improperly formatted, which was what was actually breaking the imports.
An event was manually exported from an existing project to and .ics …

Fix ical file generation

---

coderedcms/models/page_models.py
docs/releases/v0.25.1.rst
setup.py

In version 0.25.1, a fix was introduced which improved the compliance of the .ics exports of EventOccurrences. In an attempt to remove as many dependencies as possible, this change used python's builtin `timezone.utc` instead of `pytz.utc` as the timezone for `dtstart` and `dtend`. 
Unfortunately, the iCalendar package is built around using `pytz`, and throws out non compliant output when not using pytz. 
This reverts the change to using pytz, with the understanding that it will be removed when the iCalendar package is also removed.
This was tested manually by exporting an event to .ics and validating it with: https://icalendar.org/validator.html#results

Hotfix timezones on ics export

---

.prettierrc.toml
coderedcms/static/coderedcms/js/crx-events.js
coderedcms/static/coderedcms/js/crx-front.js
coderedcms/static/coderedcms/js/crx-maps.js
coderedcms/static/coderedcms/js/crx-streamforms.js
coderedcms/templates/coderedcms/includes/ical/calendar.html
coderedcms/templates/coderedcms/pages/base.html
coderedcms/templates/coderedcms/pages/event_index_page.html
coderedcms/templates/coderedcms/pages/location_index_page.html
coderedcms/templates/coderedcms/pages/stream_form_page.html

* Remove jQuery as base dependency from crx-front.js
* Remove jQuery as dependency from crx-maps.js
* Remove modernizr
* Remove date/time picker fallbacks. Modern browsers as of the past year (2021) all provide widgets for date, time, datetime-local inputs.
* Remove csrf token from ajax posts. Generally we should avoid front-end code/views which require CSRF tokens (except for actual forms) as they bust the cache.
* Update fullcalendar to 5.11.2
* Refactor map, event, and streamform code into separate scripts that live on their respective pages.
* Format javascript code with prettier
This change drops IE support from the front-end. Most functionality will continue to work in a degraded state on the front-end in IE, but support is no longer guaranteed. Wagtail 3 and Bootstrap 5 have also …

Drop jQuery, IE support

---

coderedcms/templates/coderedcms/blocks/article_block_card.html
coderedcms/templates/coderedcms/blocks/base_link_block.html
coderedcms/templates/coderedcms/blocks/card_block.html
coderedcms/templates/coderedcms/blocks/card_blurb.html
coderedcms/templates/coderedcms/blocks/card_foot.html
coderedcms/templates/coderedcms/blocks/card_head.html
coderedcms/templates/coderedcms/blocks/card_head_foot.html
coderedcms/templates/coderedcms/blocks/card_img.html
coderedcms/templates/coderedcms/blocks/carousel_block.html
coderedcms/templates/coderedcms/blocks/hero_block.html
coderedcms/templates/coderedcms/blocks/image_block.html
coderedcms/templates/coderedcms/blocks/image_gallery_block.html
coderedcms/templates/coderedcms/blocks/image_link_block.html
coderedcms/templates/coderedcms/blocks/pagelist_article_media.html
coderedcms/templates/coderedcms/blocks/pagepreview_card.html
coderedcms/templates/coderedcms/blocks/pricelistitem_block.html
coderedcms/templates/coderedcms/pages/article_index_page.html
coderedcms/templates/coderedcms/pages/article_page.html
coderedcms/templates/coderedcms/pages/article_page.search.html
coderedcms/templates/coderedcms/pages/base.html
coderedcms/templates/coderedcms/pages/event_index_page.html
coderedcms/templates/coderedcms/pages/web_page.html
coderedcms/templates/coderedcms/snippets/navbar.html
coderedcms/templates/wagtailadmin/base.html
coderedcms/views.py
docs/how_to/images.rst
docs/how_to/index.rst

See new `images.rst` doc.
All images are now served in webp format, and use more consistent sizes:
* 1600x900 for cropped images.
* 800x450 for small cropped images.
* 256x256 for small square images (e.g. blurbs)

Use WebP for images

---

coderedcms/project_template/basic/website/templates/coderedcms/pages/base.html
coderedcms/project_template/sass/website/templates/coderedcms/pages/base.html
coderedcms/templates/500.html
coderedcms/templates/coderedcms/blocks/base_link_block.html
coderedcms/templates/coderedcms/blocks/carousel_block.html
coderedcms/templates/coderedcms/blocks/image_gallery_block.html
coderedcms/templates/coderedcms/includes/ical/calendar_ical_button.html
coderedcms/templates/coderedcms/includes/ical/recurring_ical_button.html
coderedcms/templates/coderedcms/includes/ical/single_ical_button.html
coderedcms/templates/coderedcms/includes/map_list_description.html
coderedcms/templates/coderedcms/pages/article_index_page.html
coderedcms/templates/coderedcms/pages/article_page.html
coderedcms/templates/coderedcms/pages/base.html
coderedcms/templates/coderedcms/pages/event_index_page.html
coderedcms/templates/coderedcms/pages/stream_form_page.html
coderedcms/templates/coderedcms/snippets/navbar.html
coderedcms/templates/wagtailadmin/base.html

* Remove reference to `custom.css` and `custom.js` in `base.html`. They may not exist and were kept there for legacy reasons.
* Don't include optional trailing slash in self-closing HTML elements.
* Don't include optional `type` attribute in `<link>` and `<script>` tags.

Clean up HTML cruft

---

coderedcms/templates/coderedcms/includes/pagination.html

Fixes #524 
Issue was caused by a maligned line break in the django template.

Fix pagination display in django template

---

coderedcms/templates/coderedcms/blocks/cardgrid_deck.html

I made a slight change to the template which should make cards display side by side.  
Currently cards were full width and under each other using this template.
It will now work like a responsive grid row making the cards equal widths.  
Fixes #537

Fix card grid deck layout

---

coderedcms/models/page_models.py
docs/releases/index.rst
docs/releases/v1.0.3.rst

StreamForms have been broken in 1.x, however they are seldomly used. I noticed this after testing them with Wagtail 4, apparently, they were broken by Wagtail 3.
In the event that anyone was using StreamForms with 1.x, I have included a sample migration to fix the state of their database. However it is not being included with coderedcms, because I wouldn't want to blindly change `FormSubmission` objects (which is part of Wagtail, and used by other forms as well). There is also a chance the site is using a custom submission model, in which case the migration could not exist in coderedcms. If the site is experiencing an error caused by this bug, they should apply the migration themselves targeting the affected models.

Fix StreamForm submissions

---

coderedcms/blocks/base_blocks.py
coderedcms/templates/coderedcms/widgets/checkbox_classifiers.html

* Return None if "Latest Pages" block has invalid (i.e. deleted) classifier term
* Fix display issue with classifier terms in Wagtail Admin when editing a page.

Classifier bug fixes

---

coderedcms/templates/coderedcms/blocks/film_strip_block.html

Added missing semicolons in film_strip_block template. Without them, you cannot redefine both background and text colors.

Added missing semicolons in film_strip_block template

---

coderedcms/templates/coderedcms/blocks/quote_block.html

Added a closing `</figure>` tag in `quote_block.html` to fix the HTML structure and resolve #577.
N/A
This change was tested manually in the preview pane while editing a page. If you put a quote block above a text block and add the `text-center` CSS class to the quote block, you'll see the behavior.

Added closing figure tag to resolve issue #577.

---

coderedcms/views.py

.#### Description of change
Change the permission of CSV import/export and import Index to require admin permission
Created user without admin permission, checked endpoint was not accessible with that login. Logged in as admin, was able to access view.

Bug 580 Correct Permissions on CSV view

---

coderedcms/migrations/0022_auto_20210731_1853.py
coderedcms/migrations/0036_filmstrip_filmpanel.py

At some point, a few migrations slipped through referencing the concrete Image model. This of course breaks any site trying to use its own image model.

Fix use of non-dynamic image class in migrations

---

coderedcms/wagtail_hooks.py

I had a legacy form page which inherits from Wagtail's own `FormMixin`, rather than via CodeRed's models. This change simply includes those pages in the admin. My form submission results were inaccessible, otherwise.
1. Create a page model which inherits from Wagtail's forms, e.g.
```
from wagtail.contrib.forms.models import AbstractEmailForm
from wagtail.fields import RichTextField
class FormPage(AbstractEmailForm):
intro = RichTextField(blank=True)
```
2. Make migrations, and migrate.
3. Create a new page for this `FormPage` in the Wagtail admin.
4. Verify that your newly created `FormPage` is now visible under the Forms tab in the admin.

Adds Wagtail Formpages to the mix, too.

---

coderedcms/templates/coderedcms/pages/search.html
coderedcms/views.py

Workaround for: https://github.com/wagtail/wagtail/issues/11273
Basically, using `.type()` + `.search()` + MySQL search backend + paginate results, creates a bug in which there are no search results.
* Run a slightly different query to avoid the bug which returns no search results.
* Also add a fallback search result template for vanilla Wagtail pages which do not inherit from CoderedPage.

Workaround for MySQL search backend bug

---

azure-pipelines.yml
coderedcms/models/page_models.py
docs/releases/v3.0.2.rst

Currently, if a page has `index_order_by_classifier` set, and one or more of its live children have more than one `ClassifierTerm` under that classifier set, Django will return a programming error `more than one row returned by a subquery used as an expression`. 
This makes sense, as it is trying to sort on an order that is non deterministic. To fix, we slice the queryset to only ever contain a single term, which should also always be the highest order term due to the default ordering for the classifier terms.

Fix bug caused by child having multiple terms set under the index order by classifier

---

coderedcms/project_template/basic/project_name/settings/base.py
coderedcms/project_template/pro/project_name/settings/base.py
coderedcms/templates/coderedcms/blocks/article_block_card.html
coderedcms/templates/coderedcms/blocks/base_link_block.html
coderedcms/templates/coderedcms/blocks/card_block.html
coderedcms/templates/coderedcms/blocks/card_blurb.html
coderedcms/templates/coderedcms/blocks/card_foot.html
coderedcms/templates/coderedcms/blocks/card_head.html
coderedcms/templates/coderedcms/blocks/card_head_foot.html
coderedcms/templates/coderedcms/blocks/card_img.html
coderedcms/templates/coderedcms/blocks/carousel_block.html
coderedcms/templates/coderedcms/blocks/hero_block.html
coderedcms/templates/coderedcms/blocks/image_block.html
coderedcms/templates/coderedcms/blocks/image_gallery_block.html
coderedcms/templates/coderedcms/blocks/image_link_block.html
coderedcms/templates/coderedcms/blocks/pagelist_article_media.html
coderedcms/templates/coderedcms/blocks/pagepreview_card.html
coderedcms/templates/coderedcms/blocks/pricelistitem_block.html
coderedcms/templates/coderedcms/pages/article_index_page.html
coderedcms/templates/coderedcms/pages/article_page.html
coderedcms/templates/coderedcms/pages/article_page.search.html
coderedcms/templates/coderedcms/pages/base.html
coderedcms/templates/coderedcms/pages/event_index_page.html
coderedcms/templates/coderedcms/pages/page.mini.html
coderedcms/templates/coderedcms/pages/web_page.html
coderedcms/templates/coderedcms/snippets/navbar.html
coderedcms/templates/wagtailadmin/base.html
coderedcms/views.py

Add support for SVG images to the default settings in the templates of Wagtail CRX, and adds the `preserve-svg` argument to all image tags that use the `format-` argument to pass through the unaltered svg.

Add support for SVG images

---

coderedcms/templates/robots.txt

In the robots.txt file, the value of the sitemap field is a relative URL.
This should be changed to an absolute URL.
See protocol: https://sitemaps.org/protocol.html#submit_robots
For example, in the Google search console, this error message appears when it's a relative url:
> "Invalid sitemap URL" incomprehensible syntax
I think it would be interesting to have a default sitemap field in the right format using `root_url`.
What do you think of this change?

Include the absolute URL to the sitemap in the robots.txt file

---

coderedcms/templatetags/coderedcms_tags.py
docs/releases/v3.0.3.rst

Change the CRX image tag to use `get_image_model` to follow Wagtail best practices and allow for custom models
closes #621

Close bug 621 use custom image model in tag

---

coderedcms/models/snippet_models.py
coderedcms/models/tests/test_wagtailsettings_models.py
coderedcms/models/wagtailsettings_models.py
coderedcms/settings.py
coderedcms/templates/coderedcms/blocks/button_block.html
coderedcms/templates/coderedcms/blocks/download_block.html
coderedcms/templates/coderedcms/blocks/image_link_block.html
coderedcms/templates/coderedcms/includes/crx_banner.html
coderedcms/templates/coderedcms/includes/ical/calendar.html
coderedcms/templates/coderedcms/pages/base.html
coderedcms/templates/coderedcms/pages/search.html
coderedcms/templates/coderedcms/snippets/footer.html
coderedcms/templates/coderedcms/snippets/navbar.html
coderedcms/templates/wagtailadmin/base.html
coderedcms/templates/wagtailadmin/login.html
coderedcms/templatetags/coderedcms_tags.py
docs/reference/django_settings.rst
docs/releases/v3.0.3.rst

Building on the work from #623 
See settings:
* CRX_DISABLE_LAYOUT (not recommended)
* CRX_DISABLE_ANALYTICS
* CRX_DISABLE_NAVBAR
* CRX_DISABLE_FOOTER
The plan, based on what @jlchilders11 and I discussed, is to disable navbar and footer in the `pro` template, and provide a simple boilerplate navbar and footer for customization.
Note: template filters `crx_settings` and `django_settings` have been removed, and replaced with tag ` {% django_setting "MY_SETTING" %}`.

Add ability to disable built-in CRX settings

---

coderedcms/templates/wagtailadmin/login.html

Fixes #646 . Problem was due to variable scoping in django templates.

Fix site name on login screen

---

coderedcms/models/integration_models.py
coderedcms/wagtail_hooks.py

Remove a legacy wagtail_hook that was fixing an issue that no longer exists and was now causing problems.
This wagtail hook was preventing the download of documents, even when they should be
closes #671

Story 671: Remove legacy document hook

---

coderedcms/templates/wagtailforms/list_submissions.html

[Contributor Guide](https://docs.coderedcorp.com/wagtail-crx/stable/contributing/index.html).
The `wagtailforms/list_submissions.html` template is customized to use/respect protected media. This was changed in Wagtail 6.1, but was not updated to match in the CRX, causing pagination to fail to appear.

Update list submission template to match new wagtail update template

---

coderedcms/models/page_models.py
coderedcms/recaptcha.py

Certain error states in the recaptcha v3 API do not return a score. However, we were defaulting to a "good" score and therefore the errors were being let through.
This first checks if the request was successful. If so, it then compares the score.
Fallbacks have also been changed from "good" states to sentinel values, which should be helpful for debugging in production.

Fix logic for recaptcha v3 on error states

---

coderedcms/project_template/basic/pyproject.toml
coderedcms/project_template/pro/pyproject.toml

Add project table to pyproject.toml template
Otherwise, uv will fail with error message of
error: No `project` table found in: `<project_root>/pyproject.toml`
N/A
Sorry, have no idea how to unit test this.

Add project table to pyproject.toml template
