coderedcms/static/css/codered-admin.css
setup.py

Maintanence for issue #19 . Tested wagtail admin and spot-checked other functionality. Only issue was the checkbox css styling, which was fixed.
Bumping version to 0.8 since this is a major dependency change.

Upgrading to wagtail 2.2

---

coderedcms/templates/coderedcms/blocks/button_block.html
coderedcms/templates/coderedcms/pages/base.html

28-Feature-Gtag

---

coderedcms/templates/coderedcms/pages/base.html

Moving Google Analytics to head

---

coderedcms/static/css/codered-admin.css
coderedcms/static/css/codered-editor.css

Following PR #33 , here are a couple CSS changes to match the new wagtail colors.

CSS adjustments to support Wagtail 2.3

---

coderedcms/templates/coderedcms/pages/search.html

fixes #63
Note: With the heading tags I was unsure whether it was best to keep them wrapped with the logic inside or have the logic wrapping the h2. I chose the latter as it seems more readable / flexible for the slight downside of duplicating the h2. Happy to change this if it fits the overall code style better the other way

updates search page to handle no query

---

coderedcms/templates/wagtailadmin/base.forked.html
docs/releases/index.rst
docs/releases/v0.11.rst
setup.py

Not much to change here, pretty straightforward upgrade.
Also adding release notes for 0.11 with commits up to this point.

Updating to wagtail 2.4

---

coderedcms/templates/wagtailcore/password_required.html

Adding margin to top and bottom to play better with navbar and footer. Putting in a column so it isn't abnormally wide on large screens.

Tweaking password required template.

---

docs/features/import_export.rst
docs/features/store_locator.rst

Added notes to the docs for the Store Locator and Import/Export.

Docs Updates

---

coderedcms/__init__.py
docs/releases/index.rst
docs/releases/v0.12.0.rst
docs/releases/v0.12.1.rst

One commit was missing when building the 0.12 release. 0.12.1 includes all features intended for 0.12.

0.12.1 release

---

coderedcms/static/js/codered-front.js
coderedcms/templates/coderedcms/pages/base.html

Spot checked calendar and various bootstrap components, everything appears to be working well with new framework versions.

Updating bootstrap and other js frameworks

---

coderedcms/models/page_models.py

Fixes #122 
Accidentally included code from a separate issue in the last PR, it was easier to just make a new branch than try to sort the changes out.

122 Fix Event Preview 2

---

coderedcms/templates/coderedcms/pages/search.html

fixed the way the search bar sizes itself and breaks at small page width. also fixed issue with search for "none" on the page title.

fixed search bar overflow and block title name

---

coderedcms/models/page_models.py

Mark body previews safe to render html codes/entities

---

coderedcms/static/css/codered-front.css

Adding left/right/full-width styles to rich text images

---

coderedcms/__init__.py
coderedcms/static/js/codered-front.js
coderedcms/templates/coderedcms/blocks/button_block.html
coderedcms/templates/coderedcms/blocks/download_block.html
coderedcms/templates/coderedcms/blocks/hero_block.html
coderedcms/templates/coderedcms/blocks/image_link_block.html
docs/releases/index.rst
docs/releases/v0.13.1.rst

Fixes issue #143
* Fixed hero unit block to properly include content
* Fixed various GA tracking inconsistencies between Button, Download, and ImageLink blocks.
* Changed data attributes to use dashes out of paranoia

Fix bugs with new google analytics tracking

---

coderedcms/templates/coderedcms/blocks/base_link_block.html
coderedcms/templates/coderedcms/snippets/navbar.html

Missed this one in the previous pull request.

Fixing ga in navbar to use new data attrs

---

coderedcms/__init__.py
coderedcms/models/page_models.py
docs/releases/index.rst
docs/releases/v0.13.3.rst

* Fix bug when sending confirmation email with reply-to address set.
* Minor linting and code cleanup via pylint

Fix confirmation email reply-to address

---

.gitignore
coderedcms/project_template/.gitignore

Ignore editor files in new project_template projects.
Ignore multiple testproject folders in coderedcms, for example:
* testproject-feature1/
* testproject-feature2/

Ignore editor files and testprojects

---

coderedcms/templates/coderedcms/blocks/base_link_block.html
coderedcms/templatetags/coderedcms_tags.py

Slight improvement to new navbar active link feature.

Updating is_active_page to use context and check for attributes

---

coderedcms/templates/coderedcms/blocks/google_map.html
coderedcms/templates/coderedcms/blocks/rich_text_block.html

Rich text fix

---

.travis.yml

Initial travis.yml file for running unit tests

---

.travis.yml
setup.cfg
setup.py

This will fail as there are quite a few linting errors.

Implement linting with flake8 and added more python version

---

README.md
ci/run_flake8.ps1
coderedcms/__init__.py
docs/contributing/index.rst
docs/releases/index.rst
docs/releases/v0.16.0.rst
setup.py

Release notes, readme, and doc updates for 0.16 release.
Also added shiny buttons to readme.

0.16 release

---

coderedcms/models/page_models.py
docs/how_to/index.rst
docs/how_to/translation.rst
docs/index.rst
docs/releases/v0.16.0.rst

Originally provided by @niccolomineo.
I tested to make sure the `@cached_classmethod` worked, and edited documentation.

Support wagtail-modeltranslation

---

coderedcms/__init__.py
coderedcms/templates/coderedcms/pages/base.amp.html
docs/releases/index.rst
docs/releases/v0.16.1.rst

Fixing AMP template error

---

coderedcms/__init__.py
coderedcms/templatetags/coderedcms_tags.py
docs/releases/index.rst
docs/releases/v0.16.0.rst
docs/releases/v0.16.2.rst

Fix issue #247.
Should be added to the `docs/` directory. If you're not sure how to add
documentation, please provide a description here instead.
Unit tests for blocks do not exist yet... work in progress.

Fixing bug in form preview

---

.gitignore
coderedcms/models/tests/test_page_models.py

Unit test AMP pages

---

coderedcms/templates/coderedcms/snippets/navbar.html

Update to navbar.html - Search translation
[Contributor Guide](https://docs.coderedcorp.com/cms/stable/contributing/index.html).
Explain what you changed, and how or why it works the way it does.
Should be added to the `docs/` directory. If you're not sure how to add
documentation, please provide a description here instead.
Unit tests should be included to test your changes. If you're not sure how to
write unit tests, please provide a description of how to test this change
manually.

Update to navbar.html

---

azure-pipelines.yml
coderedcms/__init__.py
coderedcms/static/coderedcms/css/codered-admin.css
coderedcms/static/coderedcms/css/codered-editor.css
docs/releases/v0.17.0.rst
setup.py

Adds wagtail 2.7 to setup requirements.  Updated CSS to reflect Wagtail 2.7 admin changes.

Feature/wagtail 2.7 upgrade

---

coderedcms/blocks/__init__.py
coderedcms/blocks/base_blocks.py
coderedcms/blocks/content_blocks.py
coderedcms/blocks/html_blocks.py
coderedcms/blocks/layout_blocks.py
coderedcms/blocks/metadata_blocks.py
coderedcms/blocks/stream_form_blocks.py
coderedcms/forms.py
coderedcms/models/integration_models.py
coderedcms/models/page_models.py
coderedcms/models/snippet_models.py
coderedcms/models/wagtailsettings_models.py
coderedcms/settings.py
coderedcms/views.py
coderedcms/wagtail_flexible_forms/blocks.py
coderedcms/wagtail_flexible_forms/edit_handlers.py
coderedcms/wagtail_flexible_forms/models.py
coderedcms/wagtail_flexible_forms/wagtail_hooks.py
coderedcms/wagtail_hooks.py
setup.py

[Contributor Guide](https://docs.coderedcorp.com/cms/stable/contributing/index.html).
Explain what you changed, and how or why it works the way it does.
Should be added to the `docs/` directory. If you're not sure how to add
documentation, please provide a description here instead.
Unit tests should be included to test your changes. If you're not sure how to
write unit tests, please provide a description of how to test this change
manually.

Upgrade to Wagtail 2.8 and Django 3.0

---

setup.py

[Contributor Guide](https://docs.coderedcorp.com/cms/stable/contributing/index.html).
`django-taggit` 1.3.0 dropped today, breaking a whole lot of Wagtail stuff. This should fix it by keeping to version 1.2.0. Fixes #321.

Fix django-taggit issue.

---

coderedcms/migrations/0001_initial.py
coderedcms/models/page_models.py
coderedcms/project_template/basic/website/models.py
coderedcms/project_template/sass/website/models.py
docs/releases/v0.19.0.rst

Tested by creating a new project with a custom image model, seems to work well.
Updated release notes.

Cleanup and bug fixes related to custom image models

---

coderedcms/bin/coderedcms.py
coderedcms/project_template/basic/requirements.txt
coderedcms/project_template/sass/requirements.txt
docs/releases/v0.19.0.rst

Pin version of coderedcms in project_template requirements.txt
Fixes #333

Pin version of coderedcms in for new projects

---

coderedcms/settings.py

Fix "Outline Success" button class

---

ci/compare-codecov.ps1
ci/make-docs.ps1
ci/run-flake8.ps1
ci/run-tests.ps1
coderedcms/blocks/base_blocks.py
docs/features/blocks/baselink.rst
docs/features/blocks/button.rst
docs/features/blocks/imagelink.rst
docs/features/blocks/index.rst
docs/features/index.rst
docs/releases/v0.19.0.rst

Fixes #318 
Tested manually using a local project. Added block documentation.

Append other link to page links in BaseLinkBlock

---

docs/_static/docs.css
docs/how_to/_custom_image1.rst
docs/how_to/_custom_image2.rst
docs/how_to/_custom_image3.rst
docs/how_to/convert_image_model.rst
docs/how_to/docker.rst
docs/how_to/index.rst
docs/how_to/use_custom_image_model.rst
docs/releases/v0.19.0.rst

See discussions on Slack:
* https://wagtailcms.slack.com/archives/C81FGJR2S/p1595194543404600
* https://wagtailcms.slack.com/archives/CEU45SBRR/p1596828105203300
This is going to be a case where we can guide them in the right direction, but the hard part of doing database schema updates is on them.

Custom image model guide

---

ci/compare-codecov.ps1
ci/run-tests.ps1
docs/contributing/index.rst
setup.cfg

* Use new azure project name `cr-github`
* Move pytest command line args to setup.cfg

Update build scripts

---

.gitignore
coderedcms/static/coderedcms/css/codered-admin.css
coderedcms/static/coderedcms/css/codered-editor.css
requirements-dev.txt
setup.cfg
setup.py

Additional changes to support Wagtail 2.11. Manually tested many views in the wagtail admin to confirm CSS/visual changes are consistent.

Additional fixes for wagtail 2.11

---

coderedcms/templatetags/coderedcms_tags.py
coderedcms/tests/test_templatetags.py

Generate valid html id

---

.editorconfig
.gitattributes
coderedcms/project_template/basic/.editorconfig
coderedcms/project_template/basic/.gitattributes
coderedcms/project_template/sass/.editorconfig
coderedcms/project_template/sass/.gitattributes
docs/releases/v0.21.0.rst

Provide better developer tool boilerplate in project templates (and the main repo!)
* Updated the gitattribute files to better reflect common file types.
* Added editorconfig files as we normally use those in all our repos.
* Updated release notes.
No tests needed as these are dev tooling config files.

Update git/editor config files for repo and project templates

---

coderedcms/apps.py
coderedcms/project_template/basic/project_name/settings/base.py
coderedcms/project_template/sass/project_name/settings/base.py
coderedcms/tests/settings.py
docs/releases/v0.21.0.rst
tutorial/mysite/mysite/settings/base.py
tutorial/mysite/requirements.txt
tutorial/mysite/website/apps.py

Added settings for Default Auto Fields for Django 3.2

Django autofields

---

coderedcms/models/page_models.py
docs/releases/v0.22.0.rst

Triage for merging PR #374

---

coderedcms/models/integration_models.py
coderedcms/templates/coderedcms/formfields/mailchimp/subscriber_integration_js.html
docs/releases/index.rst
docs/releases/v0.22.1.rst

Should be patched into dev branch and cherry picked into release/0.22 branch.

Fix bug saving Mailchimp integration settings in wagtail admin

---

coderedcms/models/page_models.py

Added page link to ics invite and set a 15 minute reminder alarm (Fixes #461 )
None
Manual tests in Google, Outlook, Apple

Add event page link and reminder to calendar invites

---

coderedcms/settings.py
docs/releases/v0.23.0.rst
setup.py

Manually tested FormPage to confirm fields render properly.

Upgrade django-bootstrap4==22.1

---

coderedcms/models/page_models.py
coderedcms/models/tests/test_page_models.py
coderedcms/project_template/basic/project_name/settings/base.py
coderedcms/project_template/sass/project_name/settings/base.py
coderedcms/tests/settings.py
tutorial/mysite/mysite/settings/base.py

* Fix FormSubmission to work with Wagtail 3
* Resolve django 5 warnings
Tested manually to confirm FormSubmissions are working. Stubbed out unit test with TODOs

Fix FormSubmission to work with Wagtail 3

---

docs/releases/index.rst
docs/releases/v1.0.0.rst

Release notes for 1.0

---

coderedcms/models/wagtailsettings_models.py
docs/how_to/add_tracking_scripts.rst

* Move G- tracking setting above UA- setting since it is the more common one at this point.
* Add notes about UA deprecation by Google.
* Update tracking documentation.

Update tracking docs

---

docs/contributing/index.rst
docs/getting_started/install.rst
tutorial/mysite/website/fixtures/database.json
tutorial/mysite/website/static/website/css/custom.css

Added a fixtures database file to the tutorial project after updating some content in the tutorial site (to illustrate more pages).
Documentation on loading the database is added to the Getting Started > Installation doc.
Tested loaddata by loading the database fixture to another site and it worked.

Tutorial LoadData

---

coderedcms/blocks/html_blocks.py
coderedcms/blocks/stream_form_blocks.py
coderedcms/models/page_models.py
coderedcms/settings.py
coderedcms/tests/testapp/models.py
coderedcms/wagtail_flexible_forms/models.py

[Contributor Guide](https://docs.coderedcorp.com/wagtail-crx/stable/contributing/index.html).
Slightly modifies the logic for preview of Event pages. In the event that a preview of an event is created, and no future occurrences exist, we instead return the latest event.

Fix EventPage previews

---

coderedcms/models/page_models.py
coderedcms/models/tests/test_page_models.py
coderedcms/templates/coderedcms/pages/base.html

[Contributor Guide](https://docs.coderedcorp.com/wagtail-crx/stable/contributing/index.html).
Add custom block to `base.html` to allow for custom seo data not included by default in wagtail seo.
Cleans up logic in event page seo generation to fix errors.
Closes #552

Resolve Issues with event structured data not appearing on event pages

---

docs/how_to/docker.rst

docs: Replace waitress serve with waitress-serve
[Contributor Guide](https://docs.coderedcorp.com/wagtail-crx/stable/contributing/index.html).
Explain what you changed, and how or why it works the way it does.
Should be added to the `docs/` directory. If you're not sure how to add
documentation, please provide a description here instead.
Unit tests should be included to test your changes. If you're not sure how to
write unit tests, please provide a description of how to test this change
manually.

Correct command for waitress-serve

---

setup.py

Added in Wagtail 5.2.2. Fixes #615

Support Django 5

---

coderedcms/templates/coderedcms/pages/search.html

* Remove "is-valid" green check (makes no sense on this particular form).
* Use primary button.

Improve rendering of search form

---

coderedcms/templates/coderedcms/blocks/pagepreview_block.html

Fix template error when pagepreview page is deleted

---

azure-pipelines.yml
ci/compare-codecov.ps1

Upgrade PublishCodeCoverageResults@2

Fix pipeline deprecation warnings

---

docs/getting_started/tutorial03.rst

I've removed optional guidance to change to _variables.css since this causes issues later in the tutorial.

docs fix - prevent future issue on Blog list #685

---

coderedcms/templates/coderedcms/includes/form_button.html
coderedcms/templates/coderedcms/pages/base.html

Story: Add loading spinner and disable button on recaptcha function
